package org.ssh.bean;

// Generated Jun 19, 2014 11:05:47 AM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TTaskDelegate generated by hbm2java
 */
@Entity
@Table(name = "t_task_delegate", catalog = "test")
public class TTaskDelegate implements java.io.Serializable {

	private Integer id;
	private String userId;
	private Date delegateStart;
	private Date delegateEnd;
	private String delegateUser;

	public TTaskDelegate() {
	}

	public TTaskDelegate(String userId, Date delegateStart, Date delegateEnd,
			String delegateUser) {
		this.userId = userId;
		this.delegateStart = delegateStart;
		this.delegateEnd = delegateEnd;
		this.delegateUser = delegateUser;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "user_id", length = 64)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "delegate_start", length = 10)
	public Date getDelegateStart() {
		return this.delegateStart;
	}

	public void setDelegateStart(Date delegateStart) {
		this.delegateStart = delegateStart;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "delegate_end", length = 10)
	public Date getDelegateEnd() {
		return this.delegateEnd;
	}

	public void setDelegateEnd(Date delegateEnd) {
		this.delegateEnd = delegateEnd;
	}

	@Column(name = "delegate_user", length = 64)
	public String getDelegateUser() {
		return this.delegateUser;
	}

	public void setDelegateUser(String delegateUser) {
		this.delegateUser = delegateUser;
	}

}
